#!/bin/bash

# script to product a basic main.c entry point file

echo -n "Enter filename: "
read filename
echo -n "Enter function type: "
read funtype
echo -n "Enter function name, including parameters: "
read funname

echo -n "Want to add prototype to header file? (y/n): "
read yesNo


if [[ $yesNo == "y" || $yesNo == "Y" ]]; then
    echo -n "Please enter header file name (i.e.: main.h): "
    read headerfile
    echo $funtype $funname";" >> $headerfile
    echo -n "Prototype added to headerfile: "
    tail $headerfile;
fi

if [ $funtype == "void" ]; then
    ret="";
elif [ $funtype == "char" ]; then
    ret="return ('')";
elif [ $funtype == "string" ]; then
    ret="return (\"\");"
else
    ret="return (0);"
fi

if [ $funtype == "void" ]; then
    desret=" none - void function";
else
    desret=" describe";
fi

cat <<- EOF > $filename
#include <stdio.h>

/**
 * $funname - describe function
 *
 * @p1: describe variables in this way
 *
 * Return:$desret
 *
 */
$funtype $funname
{

/* write your code here */

$ret
}
EOF
echo "[[ filename $filename should be in this directory. open with editor to start working on it. file is written under betty standards ]]"
echo "[[ listing files in current directories: ]]"
ls -1
